### ISSUE TITLE
Legacy flag causes slightly corrupted OME-TIFF file

### ISSUE THREAD

**Issue by dsudar** [glencoesoftware/raw2ometiff#13]
When running raw2ometiff with the --legacy flag, there is some info in the file that causes tiffinfo to barf with:
...
TIFF Directory at offset 0x16be15f75 (6104899445)
  Image Width: 1408 Image Length: 1056
  Tile Width: 1024 Tile Length: 1024
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: LZW
  Photometric Interpretation: min-is-black
  Samples/Pixel: 1
  Planar Configuration: single image plane
  Software: Faas-raw2ometiff
TIFF Directory at offset 0x16be160da (6104899802)
  Image Width: 704 Image Length: 528
  Tile Width: 1024 Tile Length: 1024
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: LZW
  Photometric Interpretation: min-is-black
  Samples/Pixel: 1
  Planar Configuration: single image plane
  Software: Faas-raw2ometiff
TIFFFetchDirectory: Can not read TIFF directory count.
TIFFReadDirectory: Failed to read directory at offset 6104900095.

This was a 8-bit 2D big tiff file that was converted to n5 using bioformats2raw with --resolutions 8 and subsequently converted with raw2ometiff with --legacy flag. Without the --legacy flag, the BF6 OME-TIFF gives no issues. And btw. the slightly misshapen legacy file imports into OMERO-Plus without trouble.

**Comment by melissalinkert** [comment]
Thanks for catching this, @dsudar.  A proposed fix is in #14.
