### ISSUE TITLE
running under Java 11 gives "illegal reflective access" warnings

### ISSUE THREAD

**Issue by dsudar** [glencoesoftware/raw2ometiff#18]
When raw2ometiff runs under Java 11, it gives warnings about illegal reflective access in the org.janelia.saalfeldlab.n5.CompressionAdapter library:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.janelia.saalfeldlab.n5.CompressionAdapter (file:/usr/local/raw2ometiff-0.1.1-SNAPSHOT/lib/n5-2.1.3.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of org.janelia.saalfeldlab.n5.CompressionAdapter
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

No such problems when running under Java 8.

**Comment by melissalinkert** [comment]
https://github.com/glencoesoftware/raw2ometiff/pull/15 was merged a few days ago and should have solved this problem.  Do you still see a problem when building and running from the latest master commit?

**Comment by dsudar** [comment]
I just build a new set of bioformats2raw and raw2ometiff from whatever is committed to github. And was just able to test it. Definitely something changed but not yet for the better:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.janelia.saalfeldlab.n5.ReflectionUtils (file:/usr/local/raw2ometiff-0.1.1/lib/n5-2.1.6.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of org.janelia.saalfeldlab.n5.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by melissalinkert** [comment]
See https://github.com/glencoesoftware/bioformats2raw/issues/22#issuecomment-609464693

**Comment by chris-allan** [comment]
These warnings are safe to ignore, specific mitigation is already in place with N5 2.1.6 for Java 13. On Java 11+ you can avoid these warnings by explicitly declaring that `java.lang.reflect` deep reflection be allowed by using `--add-opens` [1] to your `JAVA_OPTS` before running `raw2ometiff`:

 * `JAVA_OPTS="--add-opens=java.base/java.lang.reflect=ALL-UNNAMED"`

1. https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-7BB28E4D-99B3-4078-BDC4-FC24180CE82B
