### ISSUE TITLE
Large output files

### ISSUE THREAD

**Issue by codybum** [glencoesoftware/raw2ometiff#26]
As posted here: https://forum.image.sc/t/converting-whole-slide-images-to-ome-tiff-a-new-workflow/32110/3

Great work, this is very much needed! While the code that comes with the Philips SDK lets us data for AI processing, we had no good solutions for pixel-level annotation of iSyntax-derived files.  A one-layer (0) Philips TIFF is around half the size of the native four-layer iSyntax file, but as you noted is not very good for viewing.

As mentioned in the blog post, the isyntax2raw conversion generates a great deal of data. For a 1.3G iSyntax file, the raw output might 20X the original size. I would expect large output for a raw extraction, which is fine if we don’t intend to store the data.  However, with default settings we noticed that the raw2ometiff also produces a rather large file compared to the iSyntax, perhaps 10X the size. 

Is such a large file expected for a OME-TIFF compared to a native iSyntax file or should I be using another compressor to reduce the size?

**Comment by melissalinkert** [comment]
I'd definitely expect the converted OME-TIFF file to be larger than the original iSyntax file by some factor.  The default settings are a place to start, but it's a good idea to experiment with different values for the ```--compression``` argument to find the right balance between file size, conversion time, and OME-TIFF tile read time for your use case.

Default LZW compression almost certainly won't result in the smallest possible file, so if file size is the main concern you might start by trying ```--compression=JPEG-2000```.  Tile sizes can impact the file size as well, so you could also experiment with different tile dimensions when running the ```isyntax2raw``` command.

**Comment by chris-allan** [comment]
Just to add to what @melissa has already said iSyntax files are lossily compressed using Philips' proprietary wavelet compression scheme. You can read more about it here:

 * https://www.philips.com/c-dam/b2bhc/master/sites/pathology/about/sdk/digital_pathology-book.pdf

raw2ometiff is not opinionated on compression choice and there are a variety of compression options available including LZW (default), JPEG, JPEG-2000 lossless and JPEG-2000 lossy. As our original article [1] says:

> Tile sizes, compression as well as file format are configurable putting these choices in the hands of clinicians, experimentalists, data scientists, and IT professionals.

  1. https://www.glencoesoftware.com/blog/2019/12/09/converting-whole-slide-images-to-OME-TIFF.html

**Comment by codybum** [comment]
Thanks for your responses!  I see the issues.  We don't really know how the Philips compression works, so we must use the Philips SDK to extract it to lossless raw format.  Since there is no comparison as to the performance of the Philips compression methods to existing known compression schemes you are defaulting to a lossless method that creates larger files, as to not degrade the image quality with another lossy compression.

**Comment by codybum** [comment]
It looks like Philips is pulling back the curtain. 

We are pleased to announce the availability of a full description of Philips’ iSyntax image format for Digital Pathology.

The following three steps are the main parts of the iSyntax image pipeline:
 
1. Write – compression of data in the iSyntax format and storing it
2. Read – reading of iSyntax data and decompressing it to create a source image
3. Post processing – processing of the source image to optimize for display to users
 
A full documentation of the above three steps, including a description of the file layout itself and accompanied by reference implementations, is now available on the Open Pathology Portal at www.openpathology.philips.com/isyntax.

**Comment by jfkotw** [comment]
I was trying to understand what the default value for the --quality option is. What are the minimum and maximum possible values? Does this change depending on which option for --compression is set?

**Comment by melissalinkert** [comment]
How the ```--quality``` flag is interpreted depends upon the value of ```--compression```.  At the moment, the only compression type for which ```--quality``` is actually used is ```JPEG-2000 Lossy```.  For that compression type, the specified quality value is the encoding rate as described in https://docs.oracle.com/cd/E17802_01/products/products/java-media/jai/forDevelopers/jai-imageio-1_0-docs/com/sun/media/imageio/plugins/jpeg2000/J2KImageWriteParam.html, and defaults to 10.

See also:

* https://github.com/ome/bioformats/blob/v6.5.1/components/formats-bsd/src/loci/formats/tiff/TiffCompression.java#L112
* https://github.com/ome/ome-codecs/blob/master/src/main/java/ome/codecs/CodecOptions.java#L110
* https://github.com/ome/ome-codecs/blob/master/src/main/java/ome/codecs/JPEG2000CodecOptions.java#L112
* https://github.com/ome/ome-codecs/blob/master/src/main/java/ome/codecs/services/JAIIIOServiceImpl.java#L121

**Comment by kaizen89** [comment]
I have also noticed the large file ouput from insyntax files. The thing is when the file is saved using the scanner directly as tiff the size is ~ 1-2 G. But when it is saved as iSyntax and then using iSyntax2raw follwed by raw2ometiff the resulting file is ~ 15G. Is there  a way to reduce the size of the tiff without loosing quality?

**Comment by sbesson** [comment]
Closing this issue since `raw2ometiff 0.6.0` was released yesterday and includes updates to the conversion workflow for RGB whole slide images to use a layout similar what is used by most vendor TIFF-based formats like SVS

In practice, converting brightfield whole slide images with the `--rgb` flag and an appropriate compression scheme like JPEG should result in significantly smaller OME-TIFF (with a 10x factor in our [tests](https://github.com/glencoesoftware/raw2ometiff/pull/113#pullrequestreview-1727688330)) without any loss of functionality.
