### ISSUE TITLE
Help to install raw2ometiff

### ISSUE THREAD

**Issue by Mohammedhusen** [glencoesoftware/raw2ometiff#32]
Hi Team,

Could you please help to install raw2ometiff in mac or Linux ?

**Comment by tabusaqri** [comment]
Hello Team,

Can you please help in the installation of raw2ometiff in mac os?

**Comment by chris-allan** [comment]
Pre-built release downloads are here:

 * https://github.com/glencoesoftware/raw2ometiff/releases

Usage is detailed here:

 * https://github.com/glencoesoftware/raw2ometiff/blob/master/README.md

If you have problems with installing the Blosc dependency for your platform, please disable compression as outlined here:

 * https://github.com/glencoesoftware/bioformats2raw/issues/34
