### ISSUE TITLE
run time on Windows Vs Unix systems 

### ISSUE THREAD

**Issue by ebiGitHub** [glencoesoftware/raw2ometiff#33]
Hello, 

I install the converter ( bioformats2raw + raw2ometiff) on both Windows and Unix  systems. 

on Unix it's runs much faster by a factor of  at least  5-10 

Can you please explain why   ?  

I need to run also on Windows  is there a way to improve the performance ?  

Best Regards

**Comment by chris-allan** [comment]
There could be any number of reasons for performance issues. Please see:

 * https://github.com/glencoesoftware/bioformats2raw#performance

Without a detailed description of your execution environment, hardware and source data I cannot say anything concrete about how you might improve performance or why you are seeing such a difference on Windows vs UNIX.
