### ISSUE TITLE
--rgb option doesn't work with 3 channel image

### ISSUE THREAD

**Issue by carlkesselman** [glencoesoftware/raw2ometiff#43]
Hi,

I have a three channel, single Z, single T CZI that I'm converting using bioformats2raw and raw2ometiff.  It looks like bioformats2raw is getting things correct, identifying three channels and three planes.  However, if the --rgb option is used, it appears that the number of planes is not being taken into consideration, and my three channel image is converted into a single rgb image:
      s.rgb = rgb && (s.c == 3) && (s.z * s.t == 1);
      if (!s.rgb) {
        s.planeCount *= s.c;
      }

Thanks,

Carl

**Comment by melissalinkert** [comment]
Also reported on https://forum.image.sc/t/conversion-of-3-channel-image/44696.  This is something that would need to be changed in bioformats2raw (to record the RGB settings from the original reader) and in raw2ometiff (to respect the original reader's RGB settings if ```--rgb``` is used).

**Comment by carlkesselman** [comment]
Just a follow up... I think that the info you need you have.  If you look in the METADATA.ome.xml it does show the channel with the correct SamplesPerPixel value in the channel and the correct number of image planes.

It works correctly if z is one, but for example, if you have multiple Z planes the above test fails, even though the metadata file seems completely correct.  

Given this, does this really require significant work to fix (or at least improve?)

Thanks,

Carl

**Comment by MosGeo** [comment]
Just tried these packages for the first time and I am hitting the same issue.

**Comment by melissalinkert** [comment]
https://github.com/glencoesoftware/raw2ometiff/pull/90 proposes some improvements to the `--rgb` flag to support multiple Z planes/timepoints/non-RGB channels.

**Comment by melissalinkert** [comment]
#90 is now merged and released in https://github.com/glencoesoftware/raw2ometiff/releases/tag/v0.4.0. If upgrading to [bioformats2raw 0.6.0](https://github.com/glencoesoftware/bioformats2raw/releases/tag/v0.6.0)/raw2ometiff 0.4.0 still shows a problem with RGB data, feel free to open a new issue.
