### ISSUE TITLE
Tile width/length must be a multiple of 16

### ISSUE THREAD

**Issue by gsakkis** [glencoesoftware/raw2ometiff#88]
After converting [CMU-1-Small-Region.svs](https://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/CMU-1-Small-Region.svs) to OME-Zarr via `bioformats2raw` and then converting the latter to OME-TIFF by `raw2ometiff`, the tile width and/or length of some pages [is not a multiple of 16](https://github.com/cgohlke/tifffile/issues/162#issuecomment-1311997881):
```
$ tiffinfo CMU-1-Small-Region.ome.tiff > /dev/null 
CMU-1-Small-Region.ome.tiff: Warning, Nonstandard tile width 387, convert file.
CMU-1-Small-Region.ome.tiff: Warning, Nonstandard tile length 463, convert file.
CMU-1-Small-Region.ome.tiff: Warning, Nonstandard tile width 387, convert file.
CMU-1-Small-Region.ome.tiff: Warning, Nonstandard tile length 463, convert file.
CMU-1-Small-Region.ome.tiff: Warning, Nonstandard tile width 387, convert file.
CMU-1-Small-Region.ome.tiff: Warning, Nonstandard tile length 463, convert file.
CMU-1-Small-Region.ome.tiff: Warning, Nonstandard tile length 431, convert file.
CMU-1-Small-Region.ome.tiff: Warning, Nonstandard tile length 431, convert file.
CMU-1-Small-Region.ome.tiff: Warning, Nonstandard tile length 431, convert file.
```

**Comment by melissalinkert** [comment]
Thanks, @gsakkis. #89 is a proposed fix; if you have a chance to try that out, we'd welcome your feedback.

**Comment by gsakkis** [comment]
@melissalinkert I tested the 0.4.0 release and the issue has indeed been resolved; thanks and apologies for the delayed reply!
